In [ ]:
# 구글 드라이브에서 파일 가져오기
from google.colab import drive

# Google Drive를 마운트
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/pytorch/non_linear.csv'

Mounted at /content/drive


In [ ]:
import pandas as pd
import torch
from torch import nn
from torch import optim
from torch.utils.data import DataLoader, TensorDataset, Dataset, random_split

In [ ]:
class CustomDataset(Dataset):
    def __init__(self,file_path):
        self.data = pd.read_csv(file_path)
        # df['x'] -> 시리즈타입
        self.x = self.data['x'].values
        self.y = self.data['y'].values
        self.length = len(self.data)

    def __getitem__(self,index):
        # custom polynominal_features
        x = torch.FloatTensor([self.x[index]**2, self.x[index]])    #입력이 2개가 됨
        y = torch.FloatTensor([self.y[index]])
        return x,y

    def __len__(self):
        return self.length

In [ ]:
# custom model을 구현

class CustomModel(nn.Module):
    # nn.Module을 상속받음
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(2,1)    # x와 x제곱 두개의 컬럼을 입력으로 사용

    def forward(self,x):
        x = self.layer(x)
        return x

In [ ]:
dataset = CustomDataset(file_path)

train_ratio = 0.8
valid_ratio = 0.1
test_ratio = 0.1

dataRatio = [train_ratio, valid_ratio, test_ratio]

dataset_size = len(dataset)
train_size = int(dataset_size * dataRatio[0])
validation_size = int(dataset_size * dataRatio[1])
test_size = dataset_size - train_size - validation_size

dataset_size, train_size, validation_size, test_size
# train_dataset, test_dataset = random_split(dataset, [train_size, test_size])

dataNum = [train_size, validation_size, test_size]

In [ ]:
train_dataset, validation_dataset, test_dataset = random_split(dataset, dataNum)
print(f'train_dataset : {len(train_dataset)}')
print(f'validation_dataset : {len(validation_dataset)}')
print(f'test_dataset : {len(test_dataset)}')

train_dataset : 160
validation_dataset : 20
test_dataset : 20


In [ ]:
train_dataloader = DataLoader(train_dataset, batch_size=16, shuffle=True, drop_last = True)
validation_dataloader = DataLoader(validation_dataset, batch_size=4, shuffle=True, drop_last = True)
test_dataloader = DataLoader(test_dataset, batch_size=4, shuffle=True, drop_last = True)

In [ ]:
count = 0
for x,y in train_dataloader:
    if count > 1:
        break
    print(x)
    print(y)
    count +=1

tensor([[ 9.0000e+00,  3.0000e+00],
        [ 8.1000e-01,  9.0000e-01],
        [ 2.5600e+00,  1.6000e+00],
        [ 1.5210e+01,  3.9000e+00],
        [ 4.0000e-02,  2.0000e-01],
        [ 6.8890e+01, -8.3000e+00],
        [ 1.9360e+01,  4.4000e+00],
        [ 2.5000e+01, -5.0000e+00],
        [ 1.0890e+01,  3.3000e+00],
        [ 1.0240e+01, -3.2000e+00],
        [ 5.1840e+01,  7.2000e+00],
        [ 4.7610e+01, -6.9000e+00],
        [ 5.4760e+01, -7.4000e+00],
        [ 9.4090e+01, -9.7000e+00],
        [ 1.2960e+01,  3.6000e+00],
        [ 9.4090e+01,  9.7000e+00]])
tensor([[ 2.3610e+01],
        [ 1.4000e+00],
        [ 6.0700e+00],
        [ 4.1170e+01],
        [-7.0000e-02],
        [ 2.2818e+02],
        [ 5.3270e+01],
        [ 8.6290e+01],
        [ 2.8540e+01],
        [ 3.7740e+01],
        [ 1.4918e+02],
        [ 1.6009e+02],
        [ 1.8324e+02],
        [ 3.0851e+02],
        [ 3.4250e+01],
        [ 2.7531e+02]])
tensor([[ 0.3600, -0.6000],
        [23.0400,  4.8000]