In [18]:
# 구글 드라이브에서 파일 가져오기
from google.colab import drive

# Google Drive를 마운트
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/pythorch/Salary.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [19]:
# 가져온 파일을 판다스로 읽어오기

import pandas as pd
import torch
from torch import nn
from torch import optim

# Google Drive에 있는 파일 경로
file_path = '/content/Salary.csv'

# CSV 파일 읽기
df = pd.read_csv(file_path)

# 데이터 확인
print(df.head())

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891


In [20]:
# 판다스로 읽어온 데이터를 numpy 형식으로 변환

df_numpy = df.to_numpy()
# print(df_numpy)

[[1.10000e+00 3.93430e+04]
 [1.30000e+00 4.62050e+04]
 [1.50000e+00 3.77310e+04]
 [2.00000e+00 4.35250e+04]
 [2.20000e+00 3.98910e+04]
 [2.90000e+00 5.66420e+04]
 [3.00000e+00 6.01500e+04]
 [3.20000e+00 5.44450e+04]
 [3.20000e+00 6.44450e+04]
 [3.70000e+00 5.71890e+04]
 [3.90000e+00 6.32180e+04]
 [4.00000e+00 5.57940e+04]
 [4.00000e+00 5.69570e+04]
 [4.10000e+00 5.70810e+04]
 [4.50000e+00 6.11110e+04]
 [4.90000e+00 6.79380e+04]
 [5.10000e+00 6.60290e+04]
 [5.30000e+00 8.30880e+04]
 [5.90000e+00 8.13630e+04]
 [6.00000e+00 9.39400e+04]
 [6.80000e+00 9.17380e+04]
 [7.10000e+00 9.82730e+04]
 [7.90000e+00 1.01302e+05]
 [8.20000e+00 1.13812e+05]
 [8.70000e+00 1.09431e+05]
 [9.00000e+00 1.05582e+05]
 [9.50000e+00 1.16969e+05]
 [9.60000e+00 1.12635e+05]
 [1.03000e+01 1.22391e+05]
 [1.05000e+01 1.21872e+05]
 [1.12000e+01 1.27345e+05]
 [1.15000e+01 1.26756e+05]
 [1.23000e+01 1.28765e+05]
 [1.29000e+01 1.35675e+05]
 [1.35000e+01 1.39465e+05]]


In [21]:
# 텐서로 변환

df_tensor = torch.tensor(df_numpy)
# print(df_tensor)

tensor([[1.1000e+00, 3.9343e+04],
        [1.3000e+00, 4.6205e+04],
        [1.5000e+00, 3.7731e+04],
        [2.0000e+00, 4.3525e+04],
        [2.2000e+00, 3.9891e+04],
        [2.9000e+00, 5.6642e+04],
        [3.0000e+00, 6.0150e+04],
        [3.2000e+00, 5.4445e+04],
        [3.2000e+00, 6.4445e+04],
        [3.7000e+00, 5.7189e+04],
        [3.9000e+00, 6.3218e+04],
        [4.0000e+00, 5.5794e+04],
        [4.0000e+00, 5.6957e+04],
        [4.1000e+00, 5.7081e+04],
        [4.5000e+00, 6.1111e+04],
        [4.9000e+00, 6.7938e+04],
        [5.1000e+00, 6.6029e+04],
        [5.3000e+00, 8.3088e+04],
        [5.9000e+00, 8.1363e+04],
        [6.0000e+00, 9.3940e+04],
        [6.8000e+00, 9.1738e+04],
        [7.1000e+00, 9.8273e+04],
        [7.9000e+00, 1.0130e+05],
        [8.2000e+00, 1.1381e+05],
        [8.7000e+00, 1.0943e+05],
        [9.0000e+00, 1.0558e+05],
        [9.5000e+00, 1.1697e+05],
        [9.6000e+00, 1.1264e+05],
        [1.0300e+01, 1.2239e+05],
        [1.050

In [26]:
# x와 y분리하기

x = df_tensor[:,0]
y = df_tensor[:,1]
# print(x)
# print(y)

# 2차원 형식으로 reshape
x = x.reshape(-1,1)
y = y.reshape(-1,1)

tensor([ 1.1000,  1.3000,  1.5000,  2.0000,  2.2000,  2.9000,  3.0000,  3.2000,
         3.2000,  3.7000,  3.9000,  4.0000,  4.0000,  4.1000,  4.5000,  4.9000,
         5.1000,  5.3000,  5.9000,  6.0000,  6.8000,  7.1000,  7.9000,  8.2000,
         8.7000,  9.0000,  9.5000,  9.6000, 10.3000, 10.5000, 11.2000, 11.5000,
        12.3000, 12.9000, 13.5000], dtype=torch.float64)
tensor([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,  54445.,
         64445.,  57189.,  63218.,  55794.,  56957.,  57081.,  61111.,  67938.,
         66029.,  83088.,  81363.,  93940.,  91738.,  98273., 101302., 113812.,
        109431., 105582., 116969., 112635., 122391., 121872., 127345., 126756.,
        128765., 135675., 139465.], dtype=torch.float64)
tensor([[ 1.1000],
        [ 1.3000],
        [ 1.5000],
        [ 2.0000],
        [ 2.2000],
        [ 2.9000],
        [ 3.0000],
        [ 3.2000],
        [ 3.2000],
        [ 3.7000],
        [ 3.9000],
        [ 4.0000],
        [ 4.0000],

In [32]:
# 데이터 스케일링
# x 데이터와 y 데이터의 규모와 범위가 너무 다름

from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler를 사용하여 0~1 사이로 스케일링
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

x_scaled = scaler_x.fit_transform(x)
y_scaled = scaler_y.fit_transform(y)

# 스케일링된 데이터를 다시 텐서로 변환
x_scaled = torch.FloatTensor(x_scaled)
y_scaled = torch.FloatTensor(y_scaled)

# print(x_scaled)
# print(y_scaled)

In [33]:
# 모델만들고 학습

#초기화
w = torch.zeros(1,requires_grad=True)
b = torch.zeros(1,requires_grad=True)
learning_rate = 0.001
EPOCH = 20000


#최적화선언
optimizer = optim.SGD([w,b],lr=learning_rate)


for epoch in range(EPOCH):
    y_pred = x_scaled * w + b
    loss = torch.mean((y_pred - y_scaled) ** 2)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 1000 == 0:
        print(f'epoch : {epoch+1}, w : {w.item():.3f}, b : {b.item():.3f}, loss : {loss:.3f}')

epoch : 1000, w : 0.280, b : 0.316, loss : 0.055
epoch : 2000, w : 0.395, b : 0.305, loss : 0.041
epoch : 3000, w : 0.483, b : 0.269, loss : 0.032
epoch : 4000, w : 0.559, b : 0.235, loss : 0.025
epoch : 5000, w : 0.625, b : 0.206, loss : 0.020
epoch : 6000, w : 0.682, b : 0.180, loss : 0.016
epoch : 7000, w : 0.731, b : 0.158, loss : 0.013
epoch : 8000, w : 0.775, b : 0.138, loss : 0.010
epoch : 9000, w : 0.812, b : 0.121, loss : 0.009
epoch : 10000, w : 0.845, b : 0.106, loss : 0.007
epoch : 11000, w : 0.873, b : 0.093, loss : 0.006
epoch : 12000, w : 0.898, b : 0.082, loss : 0.006
epoch : 13000, w : 0.920, b : 0.072, loss : 0.005
epoch : 14000, w : 0.939, b : 0.064, loss : 0.005
epoch : 15000, w : 0.955, b : 0.057, loss : 0.004
epoch : 16000, w : 0.969, b : 0.050, loss : 0.004
epoch : 17000, w : 0.981, b : 0.045, loss : 0.004
epoch : 18000, w : 0.992, b : 0.040, loss : 0.004
epoch : 19000, w : 1.002, b : 0.036, loss : 0.004
epoch : 20000, w : 1.010, b : 0.032, loss : 0.004
