In [1]:
# 텐서의 생성

import torch

# torch.tensor  vs  torch.Tensor
# tensor()는 타입변환 함수여서 값이 꼭 있어야 한다.
# Tensor()는 기본형으로 텐서인스턴스를 생성하는 클래스(기본형이 float)

torchArray1 = torch.Tensor([1,2,3,4])
torchArray2 = torch.tensor([1,2,3,4], dtype = torch.float32)

print(torchArray1)
print(torchArray2)
print(type(torchArray1))

print(torchArray1.dtype)
print(torchArray2.dtype)
print(torchArray1.device)
print(torchArray1.ndim)
print(torchArray1.shape)
print(torchArray1.size())


tensor([1., 2., 3., 4.])
tensor([1., 2., 3., 4.])
<class 'torch.Tensor'>
torch.float32
torch.float32
cpu
1
torch.Size([4])
torch.Size([4])


In [2]:
import numpy as np

# nparray = np.array([1,2,3,4])
nparray = np.array([1,2,3,4], dtype = np.float32)
print(nparray)
print(type(nparray))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [3]:
# 텐서속성

import torch

# 1행 2열짜리 난수를 생성
# tensor = torch.rand((1,2), dtype = torch.int) # 난수생성기에서는 정수타입 사용 불가
tensor = torch.rand(1,2)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

# 2행 1열로 차원 변환
tensor = tensor.reshape(2,1)
print(tensor)
print(tensor.shape)


tensor([[0.2312, 0.2945]])
torch.Size([1, 2])
torch.float32
cpu
tensor([[0.2312],
        [0.2945]])
torch.Size([2, 1])


In [4]:
# 텐서 생성 시 자료형 설정

import torch

tensor = torch.tensor([1,2,3,4], dtype = torch.float32)
print(tensor)
print(tensor.dtype)

tensor([1., 2., 3., 4.])
torch.float32


In [5]:
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
# print(tensor.device)
cpu = torch.tensor([1,2,3], device = 'cpu')
gpu = torch.tensor([1,2,3], device = 'cuda')
print(cpu)
print(gpu)
print(device)

torch.cuda.is_available()

cuda
tensor([1, 2, 3])
tensor([1, 2, 3], device='cuda:0')
cuda


True

In [6]:
# 장치를 gpu로 전환

import torch

# 장치변환으로 디바이스를 지정
# 하나의 모델을 2개 gpu로 나눠서 돌려야 할때도 사용된다.

# cpu -> gpu
gpu1 = cpu.cuda()
print(gpu1)
print(gpu1.device)


# gpu -> cpu
# cpu1 = gpu.cpu()
# print(cpu1)
# print(cpu1.device)

tensor([1, 2, 3], device='cuda:0')
cuda:0


In [7]:
# 넘파이 배열의 텐서변환
# 텐서의 넘파이 배열 변환

npArray = np.array([1,2,3,4])
print(npArray)
print(type(npArray))

# numpy -> tensor
tensor = torch.from_numpy(npArray)
print(tensor)
print(type(tensor))
print(tensor.device)    #cpu

# 넘파이 배열형태의 이미지를 신경망에 돌리려면 텐서로 변환해야하고
# 그렇게 학습된 이미지를 다시 출력하려면 넘파이 배열로 변환해야 한다.

[1 2 3 4]
<class 'numpy.ndarray'>
tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
cpu


In [8]:
# tensor -> numpy

# cpu에 있는거라서 그냥 변환됨
ndarray = tensor.numpy()
# ndarray = tensor.detach().numpy()
print(ndarray)
print(type(ndarray))    #넘파이 됨!

# 아래의 tensor는 gpu에 생성됨
tensor2 = torch.cuda.FloatTensor([1,2,3,4])
print(tensor2.device)   #cuda
# 그래서 cpu로 변환해줘야 함
# ndarray2 = tensor2.detach().cpu().numpy()
ndarray2 = tensor2.cpu().numpy()
# detach메서드 : 연산그래프에서 분리된 새로운 텐서를 반환
# 해당 텐서가 그레디언트 추적을 하는 텐서일 경우에는 detach를 반드시 해줘야함
# 위의 예제는 필수는 아님
print(ndarray2)
print(type(ndarray2))

[1 2 3 4]
<class 'numpy.ndarray'>
cuda:0
[1. 2. 3. 4.]
<class 'numpy.ndarray'>


<ipython-input-8-585c5a1c61b4>:10: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:78.)
  tensor2 = torch.cuda.FloatTensor([1,2,3,4])


In [9]:
tensor = torch.randn(3, 3, requires_grad=True)
# ndarray = tensor.numpy()  # 에러 발생: 텐서가 그래디언트를 추적 중임
# 이럴땐 반드시 detach 해줘야 함


# requires_grad = True
# 텐서가 그레디언트를 추적할지 여부를 설정하는 속성
# (손실함수의 그레디언트를 계산)

In [10]:
tensor = torch.randn(3, 3, requires_grad=True)
ndarray = tensor.detach().numpy()  # detach로 그래디언트 추적 중단 후 NumPy 변환
print(ndarray)

[[ 0.24081708 -0.5017261  -0.24585973]
 [-0.36021283 -0.4711111  -0.95065325]
 [ 1.1736467   0.26555     0.2229023 ]]


In [11]:
# 교차엔트로피

import torch
import torch.nn as nn

# 예시: 3개의 클래스 분류
output = torch.tensor([[2.0, 1.0, 0.1]])  # 모델의 예측 (logits)
target = torch.tensor([0])  # 실제 레이블 (정답 클래스 0)

criterion = nn.CrossEntropyLoss()
loss = criterion(output, target)

print(loss.item())  # 교차 엔트로피 손실 값

0.4170299470424652
