## 다중선형회귀 + 데이터로더

In [ ]:
# 필수 패키지 임포트
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader


# 데이터셋 정의
train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [ ]:
# 데이터로더
batch_size = 2
# 데이터셋을 읽어와서
train_dataset = TensorDataset(train_x,train_y)
# 데이터 로더에 데이터셋을 넣어주고 데이터로더 객체를 생성하여 아래에서 활용
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, drop_last=True)

print(train_dataset)    # train_dataset 객체
print(train_dataloader) # train_dataloader 객체


# for batch_idx, samples in enumerate(train_dataloader):
#     print(batch_idx)
#     print(samples)

In [ ]:
# 0. 하이퍼파라미터 설정
lr = 0.001
epochs = 10000

# 1. 모델 설정
model = nn.Linear(2,2, bias = True)
# 2. 손실함수 정의
criterion = nn.MSELoss()
# 3. 옵티마이저 설정
optimizer = optim.SGD(model.parameters(), lr = lr)

In [ ]:
# 4, 학습
for epoch in range(epochs):
    # 1 epoch 진행 시 3번에 나누어져서 cost가 누적
    cost = 0.0

    # 6개의 데이터를 3번에 나눠서(2개씩) 3 스텝 진행
    for batch in train_dataloader:
        x, y = batch
        # print(x,y)
        y_pred = model(x)
        loss = criterion(y_pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        # 1epoch 동안에 cost 값을 누적
        cost += loss

    cost = cost/len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f'epoch : {epoch+1:4d}, model : {list(model.parameters())}, cost : {cost:.3f}')

epoch : 1000, model : [Parameter containing:
tensor([[ 1.1150, -0.3283],
        [ 0.6391,  0.5329]], requires_grad=True), Parameter containing:
tensor([0.0049, 0.2060], requires_grad=True)], cost : 0.051
epoch : 2000, model : [Parameter containing:
tensor([[ 1.2300, -0.3877],
        [ 0.7691,  0.4657]], requires_grad=True), Parameter containing:
tensor([-0.1695,  0.0088], requires_grad=True)], cost : 0.013
epoch : 3000, model : [Parameter containing:
tensor([[ 1.2886, -0.4180],
        [ 0.8353,  0.4315]], requires_grad=True), Parameter containing:
tensor([-0.2583, -0.0916], requires_grad=True)], cost : 0.003
epoch : 4000, model : [Parameter containing:
tensor([[ 1.3184, -0.4334],
        [ 0.8690,  0.4140]], requires_grad=True), Parameter containing:
tensor([-0.3036, -0.1428], requires_grad=True)], cost : 0.001
epoch : 5000, model : [Parameter containing:
tensor([[ 1.3336, -0.4413],
        [ 0.8862,  0.4052]], requires_grad=True), Parameter containing:
tensor([-0.3266, -0.1689], re

In [ ]:
print(y_pred[:])
print(y[:])

tensor([[3.6987, 6.6997],
        [1.0036, 2.8009]], grad_fn=<SliceBackward0>)
tensor([[3.7000, 6.7000],
        [1.0000, 2.8000]])
